stages:
  - prepare
  - build

prepare:image:
  stage: prepare
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - export CONTEXT_PATH=${CI_PROJECT_DIR}
    - export DOCKERFILE_PATH=${CI_PROJECT_DIR}/Dockerfile
    - export DESTINATION_PATH=${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CONTEXT_PATH} --dockerfile ${DOCKERFILE_PATH} --destination ${DESTINATION_PATH}
  tags:
    - docker
    - linux
  rules:
    - changes:
        - Dockerfile
      when: always
    - when: manual
      allow_failure: true

build:documents:
  stage: build
  image: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
  script:
    # Build tools first.
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 -G "Unix Makefiles"
    - cmake --build . --config Release
    # Build documents.
    - ./build.py
    - find ./ -type f -printf "%P\n" | egrep "[А-Я]{4}\.[0-9]{6}\.[0-9]{3}\ ([0-9А-Я]+\ )?\([А-Яа-я ]+\)\.pdf" > .gitignore
    - git add .gitignore
    - git clean -f -d -q
    - git rm -f .gitignore
  tags:
    - docker
    - linux
  artifacts:
    untracked: true
